---
- name: Make sure host is updated, configured and k8s prerequisites are met
  become: true
  hosts: kube_cluster
  roles:
    - motd
    - containerd
    - k8s/prerequisites


- name: Test control plane node difference
  become: true
  hosts: control_plane
  roles:
    - k8s/controlplane
    - k8s/cni

- name: Test worker node difference
  hosts: worker_nodes
  become: true
  roles:
    - k8s/worker
