#!/bin/bash
tabs 4
echo "KUBERNETES CLUSTERINFO"
echo ""

CHECKFILE=/etc/kubernetes/pki/ca.key
if [ -f "CHECKFILE" ]; then
    kubectl get nodes
else
    echo "$CHECKFILE not present, cluster probably not running"
fi
