---
- name: Join cluster
  become: true
  ansible.builtin.shell: |
    kubeadm join --token {{ kubeadm_token }} \
      --discovery-token-unsafe-skip-ca-verification \
      {{ master_ip }}:6443
  register: kubeadm_join_result
  failed_when: kubeadm_join_result.rc > 1
  changed_when:
    - kubeadm_join_result.rc == 0
    - '"ERROR" not in kubeadm_join_result.stderr'
