---
- name: ensure containerd runtime is available
  ansible.builtin.apt:
    name: "containerd={{ containerd_version }}-0ubuntu1~22.04.1"
    state: present
    update_cache: yes

- name: ensure google cloud gpg key is present
  ansible.builtin.get_url:
    url: "{{ gc_gpg_keysource }}"
    dest: "{{ gc_gpg_keystore }}"
    mode: '0644'
    force: true

- name: ensure kubernetes apt repo is present
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ gc_gpg_keystore }}] {{ kubernetes_apt_repo }} kubernetes-xenial main"
    state: present

- name: ensure all required kube tools are present
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: ensure all required kube tools are held
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
