---
- name: ensure containerd runtime is available
  ansible.builtin.apt:
    name: "containerd={{ containerd_version }}-0ubuntu1~22.04.1"
    state: present
    update_cache: yes

- name: ensure containerd config path is present
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: ensure custom containerd config is present
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
  notify:
  - restart containerd

- name: flush handlers
  meta: flush_handlers
